refactor(ci): rewrite composite actions without third-party dependencies
Signed-off-by: Alessio Attilio <attilio.alessio@protonmail.com>

diff --git a/.github/actions/package/linux/action.yml b/.github/actions/package/linux/action.yml
--- a/.github/actions/package/linux/action.yml
+++ b/.github/actions/package/linux/action.yml
@@ -1,5 +1,5 @@
 name: Package for Linux
-description: Create Linux packages for PineconeMC
+description: Create Linux packages for CleanLauncher
 
 inputs:
   version:
@@ -14,20 +14,14 @@ inputs:
     required: true
     default: Linux
   qt-version:
-    description: Version of Qt to use
+    description: Version of Qt used
     required: true
-  gpg-private-key:
-    description: Private key for AppImage signing
-    required: false
-  gpg-private-key-id:
-    description: ID for the gpg-private-key, to select the signing key
-    required: false
 
 runs:
   using: composite
 
   steps:
-    - name: Cleanup Qt installation on Linux
+    - name: Cleanup Qt installation
       shell: bash
       run: |
         rm -rf "$QT_PLUGIN_PATH"/printsupport
@@ -42,23 +36,13 @@ runs:
     - name: Setup build variables
       shell: bash
       run: |
-        # Fixup architecture naming for AppImages
         dpkg_arch="$(dpkg-architecture -q DEB_HOST_ARCH_CPU)"
         case "$dpkg_arch" in
-          "amd64")
-            APPIMAGE_ARCH="x86_64"
-            ;;
-          "arm64")
-            APPIMAGE_ARCH="aarch64"
-            ;;
-          *)
-            echo "# 🚨 The Debian architecture \"$deb_arch\" is not recognized!" >> "$GITHUB_STEP_SUMMARY"
-            exit 1
-            ;;
+          "amd64") APPIMAGE_ARCH="x86_64" ;;
+          "arm64") APPIMAGE_ARCH="aarch64" ;;
+          *)       echo "::error::Unrecognized Debian architecture: $dpkg_arch"; exit 1 ;;
         esac
         echo "APPIMAGE_ARCH=$APPIMAGE_ARCH" >> "$GITHUB_ENV"
-
-        # Used for the file paths of libraries
         echo "DEB_HOST_MULTIARCH=$(dpkg-architecture -q DEB_HOST_MULTIARCH)" >> "$GITHUB_ENV"
 
     - name: Package AppImage
@@ -67,18 +51,8 @@ runs:
         VERSION: ${{ github.ref_type == 'tag' && github.ref_name || inputs.version }}
         BUILD_DIR: build
         INSTALL_APPIMAGE_DIR: install-appdir
-
-        GPG_PRIVATE_KEY: ${{ inputs.gpg-private-key }}
       run: |
-        cmake --install ${{ env.BUILD_DIR }} --config ${{ inputs.build-type }} --prefix ${{ env.INSTALL_APPIMAGE_DIR }}
-
-        if [ '${{ inputs.gpg-private-key-id }}' != '' ]; then
-          echo "$GPG_PRIVATE_KEY" > privkey.asc
-          gpg --import privkey.asc
-          gpg --export --armor ${{ inputs.gpg-private-key-id }} > pubkey.asc
-        else
-          echo ":warning: Skipped code signing for Linux AppImage, as gpg key was not present." >> $GITHUB_STEP_SUMMARY
-        fi
+        cmake --install "$BUILD_DIR" --config "${{ inputs.build-type }}" --prefix "$INSTALL_APPIMAGE_DIR"
 
         sharun lib4bin \
           --hard-links \
@@ -87,27 +61,20 @@ runs:
           "$INSTALL_APPIMAGE_DIR"/bin/* "$QT_PLUGIN_PATH"/*/*.so
 
         cp ~/bin/AppImageUpdate.AppImage "$INSTALL_APPIMAGE_DIR"/bin/
-        # FIXME(@getchoo): gamemode doesn't seem to be very portable with DBus. Find a way to make it work!
         find "$INSTALL_APPIMAGE_DIR" -name '*gamemode*' -exec rm {} +
 
-        #disable OpenGL and Vulkan launcher features until https://github.com/VHSgunzo/sharun/issues/35
-        echo "PINECONEMC_DISABLE_GLVULKAN=1" >> "$INSTALL_APPIMAGE_DIR"/.env
-        #makes the launcher use portals for file picking
+        echo "CLEANLAUNCHER_DISABLE_GLVULKAN=1" >> "$INSTALL_APPIMAGE_DIR"/.env
         echo "QT_QPA_PLATFORMTHEME=xdgdesktopportal" >> "$INSTALL_APPIMAGE_DIR"/.env
-        ln -s io.github.elyprismlauncher.ElyPrismLauncher.metainfo.xml "$INSTALL_APPIMAGE_DIR"/share/metainfo/io.github.elyprismlauncher.ElyPrismLauncher.appdata.xml
-        ln -s share/applications/io.github.elyprismlauncher.ElyPrismLauncher.desktop "$INSTALL_APPIMAGE_DIR"
-        ln -s share/icons/hicolor/256x256/apps/io.github.elyprismlauncher.ElyPrismLauncher.png "$INSTALL_APPIMAGE_DIR"
         mv "$INSTALL_APPIMAGE_DIR"/{sharun,AppRun}
-        ls -la "$INSTALL_APPIMAGE_DIR"
 
         if [[ "${{ github.ref_type }}" == "tag" ]]; then
-          APPIMAGE_DEST="PineconeMC-Linux-$APPIMAGE_ARCH.AppImage"
+          APPIMAGE_DEST="CleanLauncher-Linux-$APPIMAGE_ARCH.AppImage"
         else
-          APPIMAGE_DEST="PineconeMC-Linux-$VERSION-${{ inputs.build-type }}-$APPIMAGE_ARCH.AppImage"
+          APPIMAGE_DEST="CleanLauncher-Linux-$VERSION-${{ inputs.build-type }}-$APPIMAGE_ARCH.AppImage"
         fi
 
         mkappimage \
-          --updateinformation "gh-releases-zsync|${{ github.repository_owner }}|${{ github.event.repository.name }}|latest|PineconeMC-Linux-$APPIMAGE_ARCH.AppImage.zsync" \
+          --updateinformation "gh-releases-zsync|${{ github.repository_owner }}|${{ github.event.repository.name }}|latest|CleanLauncher-Linux-$APPIMAGE_ARCH.AppImage.zsync" \
           "$INSTALL_APPIMAGE_DIR" \
           "$APPIMAGE_DEST"
 
@@ -115,11 +82,10 @@ runs:
       shell: bash
       env:
         BUILD_DIR: build
-
         INSTALL_PORTABLE_DIR: install-portable
       run: |
-        cmake --install ${{ env.BUILD_DIR }} --config ${{ inputs.build-type }} --prefix ${{ env.INSTALL_PORTABLE_DIR }}
-        cmake --install ${{ env.BUILD_DIR }} --config ${{ inputs.build-type }} --prefix ${{ env.INSTALL_PORTABLE_DIR }} --component portable
+        cmake --install "$BUILD_DIR" --config "${{ inputs.build-type }}" --prefix "$INSTALL_PORTABLE_DIR"
+        cmake --install "$BUILD_DIR" --config "${{ inputs.build-type }}" --prefix "$INSTALL_PORTABLE_DIR" --component portable
 
         sharun lib4bin \
           --with-hooks \
@@ -127,27 +93,32 @@ runs:
           --dst-dir "$INSTALL_PORTABLE_DIR" \
           "$INSTALL_PORTABLE_DIR"/bin/* "$QT_PLUGIN_PATH"/*/*.so
 
-        # FIXME(@getchoo): gamemode doesn't seem to be very portable with DBus. Find a way to make it work!
         find "$INSTALL_PORTABLE_DIR" -name '*gamemode*' -exec rm {} +
 
-        for l in $(find ${{ env.INSTALL_PORTABLE_DIR }} -type f -o -type l); do l=${l#$(pwd)/}; l=${l#${{ env.INSTALL_PORTABLE_DIR }}/}; l=${l#./}; echo $l; done > ${{ env.INSTALL_PORTABLE_DIR }}/manifest.txt
-        cd ${{ env.INSTALL_PORTABLE_DIR }}
-        tar -czf ../PineconeMC-portable.tar.gz *
+        for l in $(find "$INSTALL_PORTABLE_DIR" -type f -o -type l); do
+          l="${l#$(pwd)/}"
+          l="${l#$INSTALL_PORTABLE_DIR/}"
+          l="${l#./}"
+          echo "$l"
+        done > "$INSTALL_PORTABLE_DIR"/manifest.txt
+
+        cd "$INSTALL_PORTABLE_DIR"
+        tar -czf ../CleanLauncher-portable.tar.gz *
 
     - name: Upload binary tarball
       uses: actions/upload-artifact@v7
       with:
-        name: PineconeMC-${{ inputs.artifact-name }}-Qt6-Portable-${{ inputs.version }}-${{ inputs.build-type }}
-        path: PineconeMC-portable.tar.gz
+        name: CleanLauncher-${{ inputs.artifact-name }}-Qt6-Portable-${{ inputs.version }}-${{ inputs.build-type }}
+        path: CleanLauncher-portable.tar.gz
 
     - name: Upload AppImage
       uses: actions/upload-artifact@v7
       with:
-        name: PineconeMC-${{ runner.os }}-${{ inputs.version }}-${{ inputs.build-type }}-${{ env.APPIMAGE_ARCH }}.AppImage
-        path: PineconeMC-${{ runner.os }}-*${{ env.APPIMAGE_ARCH }}.AppImage
+        name: CleanLauncher-${{ runner.os }}-${{ inputs.version }}-${{ inputs.build-type }}-${{ env.APPIMAGE_ARCH }}.AppImage
+        path: CleanLauncher-Linux-*${{ env.APPIMAGE_ARCH }}.AppImage
 
     - name: Upload AppImage Zsync
       uses: actions/upload-artifact@v7
       with:
-        name: PineconeMC-${{ runner.os }}-${{ inputs.version }}-${{ inputs.build-type }}-${{ env.APPIMAGE_ARCH }}.AppImage.zsync
-        path: PineconeMC-${{ runner.os }}-*${{ env.APPIMAGE_ARCH }}.AppImage.zsync
+        name: CleanLauncher-${{ runner.os }}-${{ inputs.version }}-${{ inputs.build-type }}-${{ env.APPIMAGE_ARCH }}.AppImage.zsync
+        path: CleanLauncher-Linux-*${{ env.APPIMAGE_ARCH }}.AppImage.zsync
diff --git a/.github/actions/setup-dependencies/windows/action.yml b/.github/actions/setup-dependencies/windows/action.yml
--- a/.github/actions/setup-dependencies/windows/action.yml
+++ b/.github/actions/setup-dependencies/windows/action.yml
@@ -1,5 +1,5 @@
-name: Setup Windows Dependencies
-description: Install and setup dependencies for building Prism Launcher
+name: Setup Windows dependencies
+description: Install and setup dependencies for building CleanLauncher on Windows
 
 inputs:
   build-type:
@@ -18,41 +18,26 @@ runs:
   using: composite
 
   steps:
-    # NOTE: Installed on MinGW as well for SignTool
-    - name: Enter VS Developer shell
-      if: ${{ runner.os == 'Windows' }}
-      uses: ilammy/msvc-dev-cmd@v1
-      with:
-        arch: ${{ inputs.vcvars-arch }}
-        vsversion: 2022
+    - name: Enter VS Developer shell (MSVC)
+      if: ${{ inputs.msystem == '' }}
+      shell: pwsh
+      run: |
+        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
+        $installPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
+        $vcvarsall = Join-Path $installPath "VC\Auxiliary\Build\vcvarsall.bat"
+        cmd /c "`"$vcvarsall`" ${{ inputs.vcvars-arch }} && set" | ForEach-Object {
+          if ($_ -match "^(.+?)=(.*)$") {
+            [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2], "Process")
+            "$($matches[1])=$($matches[2])" | Out-File -Append $env:GITHUB_ENV
+          }
+        }
 
     - name: Setup Java (MSVC)
+      if: ${{ inputs.msystem == '' }}
       uses: actions/setup-java@v5
       with:
-        # NOTE(@getchoo): We should probably stay on Zulu.
-        # Temurin doesn't have Java 17 builds for WoA
         distribution: zulu
         java-version: 17
-
-    - name: Setup vcpkg cache (MSVC)
-      if: ${{ inputs.msystem == '' && inputs.build-type == 'Debug' }}
-      shell: pwsh
-      env:
-        USERNAME: ${{ github.repository_owner }}
-        GITHUB_TOKEN: ${{ github.token }}
-        FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
-      run: |
-        .$(vcpkg fetch nuget) `
-          sources add `
-          -Source "$env:FEED_URL" `
-          -StorePasswordInClearText `
-          -Name GitHubPackages `
-          -UserName "$env:USERNAME" `
-          -Password "$env:GITHUB_TOKEN"
-        .$(vcpkg fetch nuget) `
-          setapikey "$env:GITHUB_TOKEN" `
-          -Source "$env:FEED_URL"
-        "VCPKG_BINARY_SOURCES=clear;nuget,$env:FEED_URL,readwrite" | Out-File -Append $env:GITHUB_ENV
 
     - name: Setup vcpkg environment (MSVC)
       if: ${{ inputs.msystem == '' }}
@@ -62,47 +47,61 @@ runs:
 
     - name: Setup MSYS2 (MinGW)
       if: ${{ inputs.msystem != '' }}
-      uses: msys2/setup-msys2@v2
-      with:
-        msystem: ${{ inputs.msystem }}
-        update: true
-        install: >-
-          git
-        pacboy: >-
-          toolchain:p
-          ccache:p
-          cmake:p
-          extra-cmake-modules:p
-          ninja:p
-          qt6-base:p
-          qt6-svg:p
-          qt6-imageformats:p
-          qt6-networkauth:p
-          cmark:p
-          qrencode:p
-          tomlplusplus:p
-          libarchive:p
+      shell: bash
+      env:
+        MSYSTEM: ${{ inputs.msystem }}
+      run: |
+        echo "C:\msys64\usr\bin" >> "$GITHUB_PATH"
+
+        case "${{ inputs.msystem }}" in
+          CLANG64)    PKG_PREFIX="mingw-w64-clang-x86_64" ;;
+          CLANGARM64) PKG_PREFIX="mingw-w64-clang-aarch64" ;;
+          MINGW64)    PKG_PREFIX="mingw-w64-x86_64" ;;
+          UCRT64)     PKG_PREFIX="mingw-w64-ucrt-x86_64" ;;
+          *)          echo "::error::Unknown msystem: ${{ inputs.msystem }}"; exit 1 ;;
+        esac
+
+        echo "PKG_PREFIX=$PKG_PREFIX" >> "$GITHUB_ENV"
+
+        C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
+
+        C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm \
+          $PKG_PREFIX-toolchain \
+          $PKG_PREFIX-ccache \
+          $PKG_PREFIX-cmake \
+          $PKG_PREFIX-extra-cmake-modules \
+          $PKG_PREFIX-ninja \
+          $PKG_PREFIX-qt6-base \
+          $PKG_PREFIX-qt6-svg \
+          $PKG_PREFIX-qt6-imageformats \
+          $PKG_PREFIX-qt6-networkauth \
+          $PKG_PREFIX-cmark \
+          $PKG_PREFIX-qrencode \
+          $PKG_PREFIX-tomlplusplus \
+          $PKG_PREFIX-libarchive"
 
     - name: List pacman packages (MinGW)
       if: ${{ inputs.msystem != '' }}
-      shell: msys2 {0}
+      shell: bash
       run: |
-        pacman -Qe
+        C:\msys64\usr\bin\bash.exe -lc "pacman -Qe"
 
     - name: Retrieve ccache cache (MinGW)
       if: ${{ inputs.msystem != '' && inputs.build-type == 'Debug' }}
-      uses: actions/cache@v5.0.5
+      uses: actions/cache@v5
       with:
         path: '${{ github.workspace }}\.ccache'
-        key: ${{ runner.os }}-mingw-w64-ccache-${{ github.run_id }}
+        key: ${{ runner.os }}-${{ inputs.msystem }}-ccache-${{ github.run_id }}
         restore-keys: |
-          ${{ runner.os }}-mingw-w64-ccache
+          ${{ runner.os }}-${{ inputs.msystem }}-ccache
 
     - name: Setup ccache (MinGW)
       if: ${{ inputs.msystem != '' && inputs.build-type == 'Debug' }}
-      shell: msys2 {0}
+      shell: bash
       run: |
-        ccache --set-config=cache_dir='${{ github.workspace }}\.ccache'
-        ccache --set-config=max_size='500M'
-        ccache --set-config=compression=true
-        ccache -p  # Show config
+        C:\msys64\usr\bin\bash.exe -lc "
+          ccache --set-config=cache_dir='${{ github.workspace }}/.ccache'
+          ccache --set-config=max_size='500M'
+          ccache --set-config=compression=true
+          ccache -p
+        "
